#!/usr/bin/env python                                                                            
#-*- coding:utf-8 -*-
from Icons import *
import GL
from PyQt4.QtGui import *
from PyQt4.QtCore import *

class Shortcut:
           
    def __init__(self, s, name, d, sk, k, cont, txt, h, i):
        #super(Shortcut, self).__init__()
        self.state = s
        self.xml = name
        self.descr = qApp.translate("action", d)
        self.standardKey = QKeySequence()
        self.standardKey = sk         
        self.key = QKeySequence(k)
        #self.key = k
        self.context = cont
        self.text = qApp.translate("action", txt)
        self.help = qApp.translate("action", h)
        self.icon = i
        self.action = QAction('', None)
        self.translated = False

sc =[ Shortcut(
         SS.STATE_INIT | SS.STATE_DISABLED | SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY | SS.STATE_SEARCH,
         "local-help",
         QT_TRANSLATE_NOOP("action","Local handbook"),
         QKeySequence.UnknownKey,
         Qt.Key_F1,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Local &Handbook..."),
         QT_TRANSLATE_NOOP("action","Show local handbook"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "file-open",
         QT_TRANSLATE_NOOP("action","File open"),
         QKeySequence.Open,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Open..."),
         QT_TRANSLATE_NOOP("action","Load score from file"),
         IconNames2.fileOpen_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "file-save",
         QT_TRANSLATE_NOOP("action","File save"),
         QKeySequence.Save,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Save"),
         QT_TRANSLATE_NOOP("action","Save score to file"),
         IconNames2.fileSave_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "file-save-as",
         QT_TRANSLATE_NOOP("action","File save as"),
         QKeySequence.SaveAs,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Save As..."),
         QT_TRANSLATE_NOOP("action","Save score under a new file name"),
         IconNames2.fileSaveAs_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "file-save-a-copy",
         QT_TRANSLATE_NOOP("action","File save a copy"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Save a Copy..."),
         QT_TRANSLATE_NOOP("action","Save a copy of the score in addition to the current file"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "file-reload",
         QT_TRANSLATE_NOOP("action","File reload"),
         QKeySequence.UnknownKey,
         0,                         # no shortcut, its an destructive non undoable operation
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Reload"),
         QT_TRANSLATE_NOOP("action","Reload score from file"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "file-close",
         QT_TRANSLATE_NOOP("action","File close"),
         QKeySequence.Close,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Close"),
         QT_TRANSLATE_NOOP("action","Close current score"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "file-new",
         QT_TRANSLATE_NOOP("action","file new"),
         Qt.CTRL+Qt.Key_N,
         0,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","New..."),
         QT_TRANSLATE_NOOP("action","Create new score"),
         IconNames2.fileNew_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "print",
         QT_TRANSLATE_NOOP("action","Print"),
         Qt.CTRL+Qt.Key_P,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Print..."),
         QT_TRANSLATE_NOOP("action","Print score"),
         IconNames2.print_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "undo",
         QT_TRANSLATE_NOOP("action","Undo"),
         QKeySequence.Undo,      # Qt.CTRL+Qt.Key_Z, # QKeySequence.Undo,
         0,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Undo"),
         QT_TRANSLATE_NOOP("action","Undo last change"),
         IconNames2.undo_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "redo",
         QT_TRANSLATE_NOOP("action","Redo"),
         QKeySequence.Redo,      # Qt.CTRL+Qt.SHIFT+Qt.Key_Z,    # QKeySequence.Redo,
         0,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Redo"),
         QT_TRANSLATE_NOOP("action","Redo last undo"),
         IconNames2.redo_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "cut",
         QT_TRANSLATE_NOOP("action","Cut"),
         Qt.CTRL+Qt.Key_X,        # QKeySequence.Cut,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Cut"),
         QT_TRANSLATE_NOOP("action",""),
         IconNames2.cut_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "copy",
         QT_TRANSLATE_NOOP("action","Copy"),
         Qt.CTRL+Qt.Key_C,        # QKeySequence.Copy,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Copy"),
         QT_TRANSLATE_NOOP("action",""),
         IconNames2.copy_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "paste",
         QT_TRANSLATE_NOOP("action","Paste"),
         Qt.CTRL+Qt.Key_V,        #  QKeySequence.Paste,
         0,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Paste"),
         QT_TRANSLATE_NOOP("action",""),
         IconNames2.paste_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "instruments",
         QT_TRANSLATE_NOOP("action","Show instruments dialog"),
         QKeySequence.UnknownKey,
         Qt.Key_I,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Instruments..."),
         QT_TRANSLATE_NOOP("action","Show instruments dialog"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "clefs",
         QT_TRANSLATE_NOOP("action","Show clefs palette"),
         QKeySequence.UnknownKey,
         Qt.Key_Y,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Clefs..."),
         QT_TRANSLATE_NOOP("action","Show clefs palette"),
         IconNames2.clef_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "keys",
         QT_TRANSLATE_NOOP("action","show keys signatures palette"),
         QKeySequence.UnknownKey,
         Qt.Key_K,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Key Signatures..."),
         QT_TRANSLATE_NOOP("action","Show key signatures palette"),
         IconNames2.sharp_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "symbols",
         QT_TRANSLATE_NOOP("action","Show symbols palette"),
         QKeySequence.UnknownKey,
         Qt.Key_Z,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Symbols..."),
         QT_TRANSLATE_NOOP("action","Show symbols palette"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "times",
         QT_TRANSLATE_NOOP("action","Show time signatures palette"),
         QKeySequence.UnknownKey,
         Qt.Key_T,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Time Signatures..."),
         QT_TRANSLATE_NOOP("action","Show time signatures palette"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "dynamics",
         QT_TRANSLATE_NOOP("action","Show dynamics palette"),
         QKeySequence.UnknownKey,
         Qt.Key_L,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Dynamics..."),
         QT_TRANSLATE_NOOP("action","Show dynamics palette"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-input",
         QT_TRANSLATE_NOOP("action","Note input mode"),
         QKeySequence.UnknownKey,
         Qt.Key_N,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Note Input"),
         QT_TRANSLATE_NOOP("action","Note input mode"),
         IconNames2.noteEntry_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pitch-spell",
         QT_TRANSLATE_NOOP("action","Pitch spell"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Pitch Spell"),
         QT_TRANSLATE_NOOP("action","Pitch spell"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval1",
         QT_TRANSLATE_NOOP("action","Enter unison above"),
         Qt.ALT + Qt.Key_1,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Unison Above"),
         QT_TRANSLATE_NOOP("action","Enter unison above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval2",
         QT_TRANSLATE_NOOP("action","Enter second above"),
         Qt.ALT + Qt.Key_2,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Second Above"),
         QT_TRANSLATE_NOOP("action","Enter second above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval3",
         QT_TRANSLATE_NOOP("action","Enter third above"),
         Qt.ALT + Qt.Key_3,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Third Above"),
         QT_TRANSLATE_NOOP("action","Enter third above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval4",
         QT_TRANSLATE_NOOP("action","Enter fourth above"),
         Qt.ALT + Qt.Key_4,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Fourth Above"),
         QT_TRANSLATE_NOOP("action","Enter fourth above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval5",
         QT_TRANSLATE_NOOP("action","Enter fifth above"),
         Qt.ALT + Qt.Key_5,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Fifth Above"),
         QT_TRANSLATE_NOOP("action","Enter fifth above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval6",
         QT_TRANSLATE_NOOP("action","Enter sixth above"),
         Qt.ALT + Qt.Key_6,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Sixth Above"),
         QT_TRANSLATE_NOOP("action","Enter sixth above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval7",
         QT_TRANSLATE_NOOP("action","Enter seventh above"),
         Qt.ALT + Qt.Key_7,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Seventh Above"),
         QT_TRANSLATE_NOOP("action","Enter seventh above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval8",
         QT_TRANSLATE_NOOP("action","Enter octave above"),
         Qt.ALT + Qt.Key_8,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Octave Above"),
         QT_TRANSLATE_NOOP("action","Enter octave above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval9",
         QT_TRANSLATE_NOOP("action","Enter ninth above"),
         Qt.ALT + Qt.Key_9,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Ninth Above"),
         QT_TRANSLATE_NOOP("action","Enter ninth above"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval-2",
         QT_TRANSLATE_NOOP("action","Enter second below"),
         Qt.SHIFT + Qt.Key_2,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Second Below"),
         QT_TRANSLATE_NOOP("action","Enter second below"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval-3",
         QT_TRANSLATE_NOOP("action","Enter third below"),
         Qt.SHIFT + Qt.Key_3,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Third Below"),
         QT_TRANSLATE_NOOP("action","Enter third below"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval-4",
         QT_TRANSLATE_NOOP("action","Enter fourth below"),
         Qt.SHIFT + Qt.Key_4,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Fourth Below"),
         QT_TRANSLATE_NOOP("action","Enter fourth below"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval-5",
         QT_TRANSLATE_NOOP("action","Enter fifth below"),
         Qt.SHIFT + Qt.Key_5,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Fifth Below"),
         QT_TRANSLATE_NOOP("action","Enter fifth below"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval-6",
         QT_TRANSLATE_NOOP("action","Enter sixth below"),
         Qt.SHIFT + Qt.Key_6,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Sixth Below"),
         QT_TRANSLATE_NOOP("action","Enter sixth below"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval-7",
         QT_TRANSLATE_NOOP("action","Enter seventh below"),
         Qt.SHIFT + Qt.Key_7,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Seventh Below"),
         QT_TRANSLATE_NOOP("action","Enter seventh below"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval-8",
         QT_TRANSLATE_NOOP("action","Enter octave below"),
         Qt.SHIFT + Qt.Key_8,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Octave Below"),
         QT_TRANSLATE_NOOP("action","Enter octave below"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "interval-9",
         QT_TRANSLATE_NOOP("action","Enter ninth below"),
         Qt.SHIFT + Qt.Key_9,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Ninth Below"),
         QT_TRANSLATE_NOOP("action","Enter ninth below"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-a",
         QT_TRANSLATE_NOOP("action","Enter note A"),
         QKeySequence.UnknownKey,
         Qt.Key_A,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","A"),
         QT_TRANSLATE_NOOP("action","Enter note A"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-b",
         QT_TRANSLATE_NOOP("action","Enter note B"),
         QKeySequence.UnknownKey,
         Qt.Key_B,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","B"),
         QT_TRANSLATE_NOOP("action","Enter note B"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-c",
         QT_TRANSLATE_NOOP("action","Enter note C"),
         QKeySequence.UnknownKey,
         Qt.Key_C,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","C"),
         QT_TRANSLATE_NOOP("action","Enter note C"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-d",
         QT_TRANSLATE_NOOP("action","Enter note D"),
         QKeySequence.UnknownKey,
         Qt.Key_D,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","D"),
         QT_TRANSLATE_NOOP("action","Enter note D"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-e",
         QT_TRANSLATE_NOOP("action","Enter note E"),
         QKeySequence.UnknownKey,
         Qt.Key_E,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","E"),
         QT_TRANSLATE_NOOP("action","Enter note E"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-f",
         QT_TRANSLATE_NOOP("action","Enter note F"),
         QKeySequence.UnknownKey,
         Qt.Key_F,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","F"),
         QT_TRANSLATE_NOOP("action","Enter note F"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-g",
         QT_TRANSLATE_NOOP("action","Enter note G"),
         QKeySequence.UnknownKey,
         Qt.Key_G,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","G"),
         QT_TRANSLATE_NOOP("action","Enter note G"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "chord-a",
         QT_TRANSLATE_NOOP("action","Add note A to chord"),
         Qt.SHIFT + Qt.Key_A,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add A"),
         QT_TRANSLATE_NOOP("action","Add note A to chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "chord-b",
         QT_TRANSLATE_NOOP("action","Add note B to chord"),
         Qt.SHIFT + Qt.Key_B,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add B"),
         QT_TRANSLATE_NOOP("action","Add note B to chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "chord-c",
         QT_TRANSLATE_NOOP("action","Add note C to chord"),
         Qt.SHIFT + Qt.Key_C,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add C"),
         QT_TRANSLATE_NOOP("action","Add note C to chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "chord-d",
         QT_TRANSLATE_NOOP("action","Add note D to chord"),
         Qt.SHIFT + Qt.Key_D,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add D"),
         QT_TRANSLATE_NOOP("action","Add note D to chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "chord-e",
         QT_TRANSLATE_NOOP("action","Add note E to chord"),
         Qt.SHIFT + Qt.Key_E,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add E"),
         QT_TRANSLATE_NOOP("action","Add note E to chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "chord-f",
         QT_TRANSLATE_NOOP("action","Add note F to chord"),
         Qt.SHIFT + Qt.Key_F,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add F"),
         QT_TRANSLATE_NOOP("action","Add note F to chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "chord-g",
         QT_TRANSLATE_NOOP("action","Add note G to chord"),
         Qt.SHIFT + Qt.Key_G,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add G"),
         QT_TRANSLATE_NOOP("action","Add note G to chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "rest",
         QT_TRANSLATE_NOOP("action","Enter rest"),
         QKeySequence.UnknownKey,
         Qt.Key_0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Rest"),
         QT_TRANSLATE_NOOP("action","Enter rest"),
          IconNames2.quartrest_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "add-staccato",
         QT_TRANSLATE_NOOP("action","Add staccato"),
         Qt.SHIFT+Qt.Key_Period,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Staccato"),
         QT_TRANSLATE_NOOP("action","Add staccato"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "add-trill",
         QT_TRANSLATE_NOOP("action","Add trill"),
         QKeySequence.UnknownKey,
	 0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Trill"),
         QT_TRANSLATE_NOOP("action","Add trill"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "stretch+",
         QT_TRANSLATE_NOOP("action","More stretch"),
         QKeySequence.UnknownKey,
         Qt.Key_BraceRight,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add More Stretch"),
         QT_TRANSLATE_NOOP("action","Add more stretch to selected measure"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "stretch-",
         QT_TRANSLATE_NOOP("action","Less stretch"),
         QKeySequence.UnknownKey,
         Qt.Key_BraceLeft,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Add Less Stretch"),
         QT_TRANSLATE_NOOP("action","Add less stretch to selected measure"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "reset-beammode",
         QT_TRANSLATE_NOOP("action","Reset Beam Mode"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Reset Beam Mode"),
         QT_TRANSLATE_NOOP("action","Reset beam mode of selected measures"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "flip",
         QT_TRANSLATE_NOOP("action","Flip direction"),
         QKeySequence.UnknownKey,
         Qt.Key_X,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Flip Direction"),
         QT_TRANSLATE_NOOP("action","Flip direction"),
         IconNames2.flip_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pitch-up",
         QT_TRANSLATE_NOOP("action","Pitch up"),
         QKeySequence.UnknownKey,
         Qt.Key_Up,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Up"),
         QT_TRANSLATE_NOOP("action","Pitch up"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pitch-up-octave",
         QT_TRANSLATE_NOOP("action","Pitch up octave"),
         Qt.CTRL + Qt.Key_Up,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Up Octave"),
         QT_TRANSLATE_NOOP("action","Pitch up by an octave"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "up-chord",
         QT_TRANSLATE_NOOP("action","Pitch up note in chord"),
         Qt.ALT+Qt.Key_Up,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Up Note in Chord"),
         QT_TRANSLATE_NOOP("action","Go to higher pitched note in chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "top-chord",
         QT_TRANSLATE_NOOP("action","Go to top note in chord"),
         Qt.ALT+Qt.CTRL+Qt.Key_Up,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Top Note in Chord"),
         QT_TRANSLATE_NOOP("action","Go to top note in chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "move-up",
         QT_TRANSLATE_NOOP("action","Move up"),
         Qt.SHIFT+Qt.CTRL+Qt.Key_Up,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","up+shift+ctrl"),
         QT_TRANSLATE_NOOP("action","up+shift+ctrl"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pitch-down",
         QT_TRANSLATE_NOOP("action","Pitch down"),
         QKeySequence.UnknownKey,
         Qt.Key_Down,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Down"),
         QT_TRANSLATE_NOOP("action","Pitch down"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pitch-down-octave",
         QT_TRANSLATE_NOOP("action","Pitch down octave"),
         Qt.CTRL + Qt.Key_Down,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Down octave"),
         QT_TRANSLATE_NOOP("action","Pitch down by an octave"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "down-chord",
         QT_TRANSLATE_NOOP("action","Pitch down note in chord"),
         Qt.ALT+Qt.Key_Down,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Down Note in Chord"),
         QT_TRANSLATE_NOOP("action","Go to lower pitched note in chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "bottom-chord",
         QT_TRANSLATE_NOOP("action","Go to bottom note in chord"),
         Qt.ALT+Qt.CTRL+Qt.Key_Down,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Bottom Note in Chord"),
         QT_TRANSLATE_NOOP("action","Go to bottom note in chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "move-down",
         QT_TRANSLATE_NOOP("action","Move down"),
         Qt.SHIFT+Qt.CTRL+Qt.Key_Down,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","down+shift+ctrl"),
         QT_TRANSLATE_NOOP("action","down+shift+ctrl"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "prev-chord",
         QT_TRANSLATE_NOOP("action","Previous chord"),
         QKeySequence.UnknownKey,
         Qt.Key_Left,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Previous Chord"),
         QT_TRANSLATE_NOOP("action","Previous chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "prev-measure",
         QT_TRANSLATE_NOOP("action","Previous measure"),
         Qt.CTRL+Qt.Key_Left,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Previous Measure"),
         QT_TRANSLATE_NOOP("action","Previous measure"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "next-chord",
         QT_TRANSLATE_NOOP("action","Next chord"),
         QKeySequence.UnknownKey,
         Qt.Key_Right,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Next Chord"),
         QT_TRANSLATE_NOOP("action","Next chord"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "next-measure",
         QT_TRANSLATE_NOOP("action","Next measure"),
         Qt.CTRL+Qt.Key_Right,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Next Measure"),
         QT_TRANSLATE_NOOP("action","Next measure"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "select-prev-chord",
         QT_TRANSLATE_NOOP("action","add previous chord to selection"),
         Qt.SHIFT+Qt.Key_Left,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","left+shift"),
         QT_TRANSLATE_NOOP("action","left+shift"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "select-prev-measure",
         QT_TRANSLATE_NOOP("action","select to beginning of measure"),
         Qt.CTRL+Qt.SHIFT+Qt.Key_Left,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","left+ctrl"),
         QT_TRANSLATE_NOOP("action","left+ctrl"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "select-next-chord",
         QT_TRANSLATE_NOOP("action","add next chord to selection"),
         Qt.SHIFT+Qt.Key_Right,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","right+shift"),
         QT_TRANSLATE_NOOP("action","right+shift"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "select-next-measure",
         QT_TRANSLATE_NOOP("action","select to end of measure"),
         Qt.CTRL+Qt.SHIFT+Qt.Key_Right,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","right+ctrl+shift"),
         QT_TRANSLATE_NOOP("action","right+ctrl+shift"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "select-begin-line",
         QT_TRANSLATE_NOOP("action","select to beginning of line"),
         Qt.SHIFT+Qt.Key_Home,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","shift+home"),
         QT_TRANSLATE_NOOP("action","shift+home"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "select-end-line",
         QT_TRANSLATE_NOOP("action","select to end of line"),
         Qt.SHIFT+Qt.Key_End,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","shift+end"),
         QT_TRANSLATE_NOOP("action","shift+end"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "select-begin-score",
         QT_TRANSLATE_NOOP("action","select to beginning of score"),
         Qt.CTRL+Qt.SHIFT+Qt.Key_Home,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","ctrl+shift+home"),
         QT_TRANSLATE_NOOP("action","ctrl+shift+home"),
         0
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "select-end-score",
         QT_TRANSLATE_NOOP("action","select to end of score"),
         Qt.CTRL+Qt.SHIFT+Qt.Key_End,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","ctrl+shift+end"),
         QT_TRANSLATE_NOOP("action","ctrl+shift+end"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "select-staff-above",
         QT_TRANSLATE_NOOP("action","add staff above to selection"),
         Qt.SHIFT+Qt.Key_Up,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","add staff above to selection"),
         QT_TRANSLATE_NOOP("action","add staff above to selection"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "select-staff-below",
         QT_TRANSLATE_NOOP("action","add staff below to selection"),
         Qt.SHIFT+Qt.Key_Down,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","add staff below to selection"),
         QT_TRANSLATE_NOOP("action","add staff below to selection"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "page-prev",
         QT_TRANSLATE_NOOP("action","page-prev"),
         QKeySequence.UnknownKey,
         Qt.Key_PageUp,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "page-next",
         QT_TRANSLATE_NOOP("action","page-next"),
         QKeySequence.UnknownKey,
         Qt.Key_PageDown,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "page-top",
         QT_TRANSLATE_NOOP("action","page-top"),
         QKeySequence.UnknownKey,
         Qt.Key_Home,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "page-end",
         QT_TRANSLATE_NOOP("action","page-end"),
         QKeySequence.UnknownKey,
         Qt.Key_End,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "add-slur",
         QT_TRANSLATE_NOOP("action","add slur"),
         QKeySequence.UnknownKey,
         Qt.Key_S,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "add-hairpin",
         QT_TRANSLATE_NOOP("action","crescendo"),
         QKeySequence.UnknownKey,
         Qt.Key_H,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "add-hairpin-reverse",
         QT_TRANSLATE_NOOP("action","decrescendo"),
         Qt.SHIFT+Qt.Key_H,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY | SS.STATE_SEARCH,
         "escape",
         QT_TRANSLATE_NOOP("action","ESCAPE"),
         QKeySequence.UnknownKey,
         Qt.Key_Escape,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "delete",
         QT_TRANSLATE_NOOP("action","Delete"),
         QKeySequence.UnknownKey,
         Qt.Key_Delete,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Delete"),
         QT_TRANSLATE_NOOP("action","Delete contents of the selected measures"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "time-delete",
         QT_TRANSLATE_NOOP("action","Timewise Delete"),
         QKeySequence.UnknownKey,
         0, # Qt.CTRL + Qt.Key_Delete,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Timewise Delete"),
         QT_TRANSLATE_NOOP("action","Delete element and duration"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "delete-measures",
         QT_TRANSLATE_NOOP("action","Delete selected measures"),
         Qt.CTRL + Qt.Key_Delete,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Delete Selected Measures"),
         QT_TRANSLATE_NOOP("action","Delete selected measures"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "append-measure",
         QT_TRANSLATE_NOOP("action","Append measure"),      # Appears in Edit > Preferences > Shortcuts
         Qt.CTRL+Qt.Key_B,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Append Measure"),       # Appears in menu
         QT_TRANSLATE_NOOP("action","Append Measure"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "append-measures",
         QT_TRANSLATE_NOOP("action","Append measures"),
         Qt.CTRL+Qt.SHIFT+Qt.Key_B,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Append Measures..."),
         QT_TRANSLATE_NOOP("action","Append Measures..."),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "insert-measure",
         QT_TRANSLATE_NOOP("action","Insert measure"),
         QKeySequence.UnknownKey,
         Qt.Key_Insert,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Insert Measure"),
         QT_TRANSLATE_NOOP("action","Insert Measure"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "insert-measures",
         QT_TRANSLATE_NOOP("action","Insert measures"),
         Qt.CTRL+Qt.Key_Insert,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Insert Measures..."),
         QT_TRANSLATE_NOOP("action","Insert Measures..."),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "insert-hbox",
         QT_TRANSLATE_NOOP("action","Insert Horizontal Frame"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Insert Horizontal Frame"),
         QT_TRANSLATE_NOOP("action","Insert Horizontal Frame"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "insert-vbox",
         QT_TRANSLATE_NOOP("action","Insert Vertical Frame"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Insert Vertical Frame"),
         QT_TRANSLATE_NOOP("action","Insert Vertical Frame"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "append-hbox",
         QT_TRANSLATE_NOOP("action","Append Horizontal Frame"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Append Horizontal Frame"),
         QT_TRANSLATE_NOOP("action","Append Horizontal Frame"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "append-vbox",
         QT_TRANSLATE_NOOP("action","Append Vertical Frame"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Append Vertical Frame"),
         QT_TRANSLATE_NOOP("action","Append Vertical Frame"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "duplet",
         QT_TRANSLATE_NOOP("action","Duplet"),
         Qt.CTRL+Qt.Key_2,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Duplet"),
         QT_TRANSLATE_NOOP("action","Duplet"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "triplet",
         QT_TRANSLATE_NOOP("action","Triplet"),
         Qt.CTRL+Qt.Key_3,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Triplet"),
         QT_TRANSLATE_NOOP("action","Triplet"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "quadruplet",
         QT_TRANSLATE_NOOP("action","Quadruplet"),
         Qt.CTRL+Qt.Key_4,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Quadruplet"),
         QT_TRANSLATE_NOOP("action","Quadruplet"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "quintuplet",
         QT_TRANSLATE_NOOP("action","Quintuplet"),
         Qt.CTRL+Qt.Key_5,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Quintuplet"),
         QT_TRANSLATE_NOOP("action","Quintuplet"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "sextuplet",
         QT_TRANSLATE_NOOP("action","Sextuplet"),
         Qt.CTRL+Qt.Key_6,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Sextuplet"),
         QT_TRANSLATE_NOOP("action","Sextuplet"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "septuplet",
         QT_TRANSLATE_NOOP("action","Septuplet"),
         Qt.CTRL+Qt.Key_7,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Septuplet"),
         QT_TRANSLATE_NOOP("action","Septuplet"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "octuplet",
         QT_TRANSLATE_NOOP("action","Octuplet"),
         Qt.CTRL+Qt.Key_8,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Octuplet"),
         QT_TRANSLATE_NOOP("action","Octuplet"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "nonuplet",
         QT_TRANSLATE_NOOP("action","Nonuplet"),
         Qt.CTRL+Qt.Key_9,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Nonuplet"),
         QT_TRANSLATE_NOOP("action","Nonuplet"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "tuplet-dialog",
         QT_TRANSLATE_NOOP("action","Other Tuplets"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Other..."),
         QT_TRANSLATE_NOOP("action","Other..."),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-longa",
         QT_TRANSLATE_NOOP("action","note longa"),
         QKeySequence.UnknownKey,
         Qt.Key_9,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Longa"),
         QT_TRANSLATE_NOOP("action","Longa"),
         IconNames2.longaUp_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "note-breve",
         QT_TRANSLATE_NOOP("action","note breve"),
         QKeySequence.UnknownKey,
         Qt.Key_8,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Double whole note (breve)"),
         QT_TRANSLATE_NOOP("action","Double whole note (breve)"),
         IconNames2.brevis_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-note-1",
         QT_TRANSLATE_NOOP("action","pad note 1/1"),
         QKeySequence.UnknownKey,
         Qt.Key_7,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Whole note (semibreve)"),
         QT_TRANSLATE_NOOP("action","Whole note (semibreve)"),
         IconNames2.note_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-note-2",
         QT_TRANSLATE_NOOP("action","pad note 1/2"),
         QKeySequence.UnknownKey,
         Qt.Key_6,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Half note (minim)"),
         QT_TRANSLATE_NOOP("action","Half note (minim)"),
         IconNames2.note2_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-note-4",
         QT_TRANSLATE_NOOP("action","pad note 1/4"),
         QKeySequence.UnknownKey,
         Qt.Key_5,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Quarter note (crochet)"),
         QT_TRANSLATE_NOOP("action","Quarter note (crochet)"),
         IconNames2.note4_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-note-8",
         QT_TRANSLATE_NOOP("action","pad note 1/8"),
         QKeySequence.UnknownKey,
         Qt.Key_4,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Eighth note (quaver)"),
         QT_TRANSLATE_NOOP("action","Eighth note (quaver)"),
         IconNames2.note8_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-note-16",
         QT_TRANSLATE_NOOP("action","pad note 1/16"),
         QKeySequence.UnknownKey,
         Qt.Key_3,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","16th note (semiquaver)"),
         QT_TRANSLATE_NOOP("action","16th note (semiquaver)"),
         IconNames2.note16_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-note-32",
         QT_TRANSLATE_NOOP("action","pad note 1/32"),
         QKeySequence.UnknownKey,
         Qt.Key_2,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","32nd note (demi-semiquaver)"),
         QT_TRANSLATE_NOOP("action","32nd note (demi-semiquaver)"),
         IconNames2.note32_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-note-64",
         QT_TRANSLATE_NOOP("action","pad note 1/64"),
         QKeySequence.UnknownKey,
         Qt.Key_1,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","64th note (semi-demi-semiquaver)"),
         QT_TRANSLATE_NOOP("action","64th note (semi-demi-semiquaver)"),
         IconNames2.note64_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-dot",
         QT_TRANSLATE_NOOP("action","pad dot"),
         QKeySequence.UnknownKey,
         Qt.Key_Period,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Dot"),
         QT_TRANSLATE_NOOP("action","Dot"),
         IconNames2.dot_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-dotdot",
         QT_TRANSLATE_NOOP("action","pad double dot"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Double dot"),
         QT_TRANSLATE_NOOP("action","Double dot"),
         IconNames2.dotdot_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "tie",
         QT_TRANSLATE_NOOP("action","tie"),
         QKeySequence.UnknownKey,
         Qt.Key_Plus,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","tie"),
         QT_TRANSLATE_NOOP("action","tie"),
         IconNames2.tie_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-rest",
         QT_TRANSLATE_NOOP("action","pad rest"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","rest"),
         QT_TRANSLATE_NOOP("action","rest"),
         IconNames2.quartrest_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "sharp2",
         QT_TRANSLATE_NOOP("action","double sharp"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","double sharp"),
         QT_TRANSLATE_NOOP("action","double sharp"),
         IconNames2.sharpsharp_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "sharp",
         QT_TRANSLATE_NOOP("action","sharp"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","sharp"),
         QT_TRANSLATE_NOOP("action","sharp"),
         IconNames2.sharp_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "nat",
         QT_TRANSLATE_NOOP("action","natural"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","natural"),
         QT_TRANSLATE_NOOP("action","natural"),
         IconNames2.natural_ICON
         ),
       Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "flat",
         QT_TRANSLATE_NOOP("action","Flat"),
         QKeySequence.UnknownKey,
         Qt.Key_Minus,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Flat"),
         QT_TRANSLATE_NOOP("action","Flat"),
         IconNames2.flat_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "flat2",
         QT_TRANSLATE_NOOP("action","double flat"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","double flat"),
         QT_TRANSLATE_NOOP("action","double flat"),
         IconNames2.flatflat_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-acciaccatura",
         QT_TRANSLATE_NOOP("action","acciaccatura"),
         QKeySequence.UnknownKey,
         Qt.Key_Slash,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","acciaccatura"),
         QT_TRANSLATE_NOOP("action","acciaccatura"),
         IconNames2.acciaccatura_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "pad-appoggiatura",
         QT_TRANSLATE_NOOP("action","appoggiatura"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","appoggiatura"),
         QT_TRANSLATE_NOOP("action","appoggiatura"),
         IconNames2.appoggiatura_ICON
         ),
      Shortcut(
        SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
        "pad-grace4",
        QT_TRANSLATE_NOOP("action","grace-4"),
        QKeySequence.UnknownKey,
        0,
        Qt.WindowShortcut,
        QT_TRANSLATE_NOOP("action","grace-4"),
        QT_TRANSLATE_NOOP("action","grace-4"),
        IconNames2.grace4_ICON
        ),
     Shortcut(
        SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
        "pad-grace16",
        QT_TRANSLATE_NOOP("action","grace-16"),
        QKeySequence.UnknownKey,
        0,
        Qt.WindowShortcut,
        QT_TRANSLATE_NOOP("action","grace-16"),
        QT_TRANSLATE_NOOP("action","grace-16"),
        IconNames2.grace16_ICON
        ),
     Shortcut(
        SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
        "pad-grace32",
        QT_TRANSLATE_NOOP("action","grace-32"),
        QKeySequence.UnknownKey,
        0,
        Qt.WindowShortcut,
        QT_TRANSLATE_NOOP("action","grace-32"),
        QT_TRANSLATE_NOOP("action","grace-32"),
        IconNames2.grace32_ICON
        ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "voice-1",
         QT_TRANSLATE_NOOP("action","voice 1"),
         Qt.ALT+Qt.CTRL+Qt.Key_1,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","voice 1"),
         QT_TRANSLATE_NOOP("action","voice 1"),
         IconNames2.voice1_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "voice-2",
         QT_TRANSLATE_NOOP("action","voice 2"),
         Qt.ALT+Qt.CTRL+Qt.Key_2,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","voice 2"),
         QT_TRANSLATE_NOOP("action","voice 2"),
         IconNames2.voice2_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "voice-3",
         QT_TRANSLATE_NOOP("action","voice 3"),
         Qt.ALT+Qt.CTRL+Qt.Key_3,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","voice 3"),
         QT_TRANSLATE_NOOP("action","voice 3"),
         IconNames2.voice3_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "voice-4",
         QT_TRANSLATE_NOOP("action","voice 4"),
         Qt.ALT+Qt.CTRL+Qt.Key_4,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","voice 4"),
         QT_TRANSLATE_NOOP("action","voice 4"),
         IconNames2.voice4_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "midi-on",
         QT_TRANSLATE_NOOP("action","midi input in"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Enable MIDI Input"),
         QT_TRANSLATE_NOOP("action","Enable MIDI Input"),
         IconNames2.midiin_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "sound-on",
         QT_TRANSLATE_NOOP("action","editing sound on"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Enable sound while editing"),
         QT_TRANSLATE_NOOP("action","Enable sound while editing"),
         IconNames2.speaker_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "beam-start",
         QT_TRANSLATE_NOOP("action","beam start"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","beam start"),
         QT_TRANSLATE_NOOP("action","beam start"),
         IconNames2.sbeam_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "beam-mid",
         QT_TRANSLATE_NOOP("action","beam mid"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","beam mid"),
         QT_TRANSLATE_NOOP("action","beam mid"),
         IconNames2.mbeam_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "no-beam",
         QT_TRANSLATE_NOOP("action","no beam"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","no beam"),
         QT_TRANSLATE_NOOP("action","no beam"),
         IconNames2.nbeam_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "beam32",
         QT_TRANSLATE_NOOP("action","beam 32"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","beam 32"),
         QT_TRANSLATE_NOOP("action","beam 32"),
         IconNames2.beam32_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "auto-beam",
         QT_TRANSLATE_NOOP("action","auto beam"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","auto beam"),
         QT_TRANSLATE_NOOP("action","auto beam"),
         IconNames2.abeam_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "toggle-palette",
         QT_TRANSLATE_NOOP("action","Palette"),
         QKeySequence.UnknownKey,
	 Qt.Key_F9,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Palette"),
         QT_TRANSLATE_NOOP("action","Palette"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "toggle-playpanel",
         QT_TRANSLATE_NOOP("action","Play Panel"),
         QKeySequence.UnknownKey,
	 Qt.Key_F11,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Play Panel"),
         QT_TRANSLATE_NOOP("action","Play Panel"),
         0
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "toggle-navigator",
         QT_TRANSLATE_NOOP("action","Navigator"),
         QKeySequence.UnknownKey,
	 Qt.Key_F12,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Navigator"),
         QT_TRANSLATE_NOOP("action","Navigator"),
         -1
         ),
      Shortcut(

	 SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "toggle-mixer",
         QT_TRANSLATE_NOOP("action","Mixer"),
         QKeySequence.UnknownKey,
	 Qt.Key_F10,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Mixer"),
         QT_TRANSLATE_NOOP("action","Mixer"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "toggle-transport",
         QT_TRANSLATE_NOOP("action","Transport Toolbar"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Transport"),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "toggle-noteinput",
         QT_TRANSLATE_NOOP("action","Note Input Toolbar"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Note Input"),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "toggle-statusbar",
         QT_TRANSLATE_NOOP("action","Status Bar"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Status Bar"),
         QT_TRANSLATE_NOOP("action","Status Bar"),
         -1
         ),

      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "quit",
         QT_TRANSLATE_NOOP("action","Quit"),
         Qt.CTRL + Qt.Key_Q,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Quit"),
         QT_TRANSLATE_NOOP("action","Quit"),
         IconNames2.exit_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         "mag",
         QT_TRANSLATE_NOOP("action","Mag"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Mag"),
         QT_TRANSLATE_NOOP("action","Zoom Canvas"),
         IconNames2.viewmag_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "lyrics",
         QT_TRANSLATE_NOOP("action","Lyrics"),
         Qt.CTRL + Qt.Key_L,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Lyrics"),
         QT_TRANSLATE_NOOP("action","Lyrics"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "fingering",
         QT_TRANSLATE_NOOP("action","Fingering Palette"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Fingering..."),
         QT_TRANSLATE_NOOP("action","Fingering"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "tempo",
         QT_TRANSLATE_NOOP("action","Tempo Palette"),
         Qt.CTRL+Qt.ALT + Qt.Key_T,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Tempo..."),
         QT_TRANSLATE_NOOP("action","Tempo"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "metronome",
         QT_TRANSLATE_NOOP("action","Metronome"),
         Qt.CTRL+Qt.ALT + Qt.Key_M,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Metronome"),
         QT_TRANSLATE_NOOP("action","Metronome"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "system-text",
         QT_TRANSLATE_NOOP("action","Add System Text"),
         Qt.CTRL + Qt.SHIFT + Qt.Key_T,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","System Text"),
         QT_TRANSLATE_NOOP("action","Add System Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "staff-text",
         QT_TRANSLATE_NOOP("action","Add Staff Text"),
         Qt.CTRL + Qt.Key_T,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Staff Text"),
         QT_TRANSLATE_NOOP("action","Add Staff Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "frame-text",
         QT_TRANSLATE_NOOP("action","Add Text"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Frame Text"),
         QT_TRANSLATE_NOOP("action","Add Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "title-text",
         QT_TRANSLATE_NOOP("action","Add Title"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Title"),
         QT_TRANSLATE_NOOP("action","Add Title Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "subtitle-text",
         QT_TRANSLATE_NOOP("action","Add Subtitle"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Subtitle"),
         QT_TRANSLATE_NOOP("action","Add Subtitle Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "composer-text",
         QT_TRANSLATE_NOOP("action","Add Composer"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Composer"),
         QT_TRANSLATE_NOOP("action","Add Composer Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "poet-text",
         QT_TRANSLATE_NOOP("action","Add Poet"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Poet"),
         QT_TRANSLATE_NOOP("action","Add Poet Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "copyright-text",
         QT_TRANSLATE_NOOP("action","Add Copyright"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Copyright"),
         QT_TRANSLATE_NOOP("action","Add Copyright Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "chord-text",
         QT_TRANSLATE_NOOP("action","Add Chord Name"),
         Qt.CTRL + Qt.Key_K,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Chord Name"),
         QT_TRANSLATE_NOOP("action","Add Chord Text"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "harmony-properties",
         QT_TRANSLATE_NOOP("action","show harmony properties for chord"),
         Qt.SHIFT+Qt.Key_K,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Harmony Properties"),
         QT_TRANSLATE_NOOP("action","Harmony Properties"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "rehearsalmark-text",
         QT_TRANSLATE_NOOP("action","Add Rehearsal Mark"),
         Qt.CTRL + Qt.Key_M,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Rehearsal Mark"),
         QT_TRANSLATE_NOOP("action","Add Rehearsal Mark"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "play",
         QT_TRANSLATE_NOOP("action","Player play"),
         QKeySequence.UnknownKey,
         Qt.Key_Space,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Play"),
         QT_TRANSLATE_NOOP("action","Start or stop playback"),
         IconNames2.play_ICON
         ),
      Shortcut(
         SS.STATE_PLAY,
         "play-prev-chord",
         QT_TRANSLATE_NOOP("action","Previous chord"),
         QKeySequence.UnknownKey,
         Qt.Key_Left,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Previous chord"),
         QT_TRANSLATE_NOOP("action","Previous chord"),
         -1
         ),
      Shortcut(
         SS.STATE_PLAY,
         "play-prev-measure",
         QT_TRANSLATE_NOOP("action","Previous measure"),
         QKeySequence.UnknownKey,
         Qt.CTRL+Qt.Key_Left,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Previous measure"),
         QT_TRANSLATE_NOOP("action","Previous measure"),
         -1
         ),
      Shortcut(
         SS.STATE_PLAY,
         "play-next-chord",
         QT_TRANSLATE_NOOP("action","Next chord"),
         QKeySequence.UnknownKey,
         Qt.Key_Right,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Next chord"),
         QT_TRANSLATE_NOOP("action","Next chord"),
         -1
         ),
      Shortcut(
         SS.STATE_PLAY,
         "play-next-measure",
         QT_TRANSLATE_NOOP("action","Next measure"),
         Qt.CTRL+Qt.Key_Right,
         0,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","Next measure"),
         QT_TRANSLATE_NOOP("action","Next measure"),
         -1
         ),
      Shortcut(
         SS.STATE_PLAY,
         "seek-begin",
         QT_TRANSLATE_NOOP("action","Seek to begin"),
         QKeySequence.UnknownKey,
         Qt.Key_Home,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "rewind",
         QT_TRANSLATE_NOOP("action","Player rewind"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Rewind"),
         QT_TRANSLATE_NOOP("action","Rewind to start position"),
         IconNames2.start_ICON
         ),
      Shortcut(
         SS.STATE_PLAY,
         "seek-end",
         QT_TRANSLATE_NOOP("action","Seek to end"),
         QKeySequence.UnknownKey,
         Qt.Key_End,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action",""),
         QT_TRANSLATE_NOOP("action",""),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "repeat",
         QT_TRANSLATE_NOOP("action","Play repeats on/off"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Repeat"),
         QT_TRANSLATE_NOOP("action","Play repeats on/off"),
         IconNames2.repeat_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "load-style",
         QT_TRANSLATE_NOOP("action","Load style"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Load Style..."),
         QT_TRANSLATE_NOOP("action","Load Style"),
         IconNames2.fileOpen_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "save-style",
         QT_TRANSLATE_NOOP("action","Save style"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Save Style..."),
         QT_TRANSLATE_NOOP("action","Save Style"),
         IconNames2.fileSave_ICON
         ),
      Shortcut (
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "select-all",
         QT_TRANSLATE_NOOP("action","Select all"),
         Qt.CTRL+Qt.Key_A,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Select All"),
         QT_TRANSLATE_NOOP("action","Select All"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL,
         "transpose",
         QT_TRANSLATE_NOOP("action","Transpose"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Transpose..."),
         QT_TRANSLATE_NOOP("action","Transpose"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "clef-violin",
         QT_TRANSLATE_NOOP("action","violin clef"),
         QKeySequence(Qt.CTRL+Qt.Key_Y, Qt.CTRL+Qt.Key_1),
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","violin clef"),
         QT_TRANSLATE_NOOP("action","violin clef"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "clef-bass",
         QT_TRANSLATE_NOOP("action","bass clef"),
         QKeySequence(Qt.CTRL+Qt.Key_Y, Qt.CTRL+Qt.Key_2),
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","bass clef"),
         QT_TRANSLATE_NOOP("action","bass clef"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL,
         "voice-x12",
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-2"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-2"),
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-2"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL,
         "voice-x13",
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-3"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-3"),
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-3"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL,
         "voice-x14",
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-4"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-4"),
         QT_TRANSLATE_NOOP("action","Exchange Voice 1-4"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL,
         "voice-x23",
         QT_TRANSLATE_NOOP("action","Exchange Voice 2-3"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Exchange Voice 2-3"),
         QT_TRANSLATE_NOOP("action","Exchange Voice 2-3"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL,
         "voice-x24",
         QT_TRANSLATE_NOOP("action","Exchange Voice 2-4"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Exchange Voice 2-4"),
         QT_TRANSLATE_NOOP("action","Exchange Voice 2-4"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL,
         "voice-x34",
         QT_TRANSLATE_NOOP("action","Exchange Voice 3-4"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Exchange Voice 3-4"),
         QT_TRANSLATE_NOOP("action","Exchange Voice 3-4"),
         -1
         ),
      Shortcut (
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "concert-pitch",
         QT_TRANSLATE_NOOP("action","display in concert pitch"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Concert Pitch"),
         QT_TRANSLATE_NOOP("action","Display in Concert Pitch"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "repeat-cmd",
         QT_TRANSLATE_NOOP("action","repeat last command"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Repeat last command"),
         QT_TRANSLATE_NOOP("action","Repeat last command"),
         IconNames2.fileOpen_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "edit-meta",
         QT_TRANSLATE_NOOP("action","edit score meta data"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Meta Data..."),
         QT_TRANSLATE_NOOP("action","Meta Data"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "system-break",
         QT_TRANSLATE_NOOP("action","toggle system break"),
         QKeySequence.UnknownKey,
         Qt.Key_Return,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Toggle System Break"),
         QT_TRANSLATE_NOOP("action","Toggle System Break"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "page-break",
         QT_TRANSLATE_NOOP("action","toggle page break"),
         Qt.CTRL+Qt.Key_Return,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Toggle Page Break"),
         QT_TRANSLATE_NOOP("action","Toggle Page Break"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "edit-element",
         QT_TRANSLATE_NOOP("action","edit element"),
         Qt.CTRL+Qt.Key_E,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Edit Element"),
         QT_TRANSLATE_NOOP("action","Edit Element"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "reset-positions",
         QT_TRANSLATE_NOOP("action","reset positions"),
         Qt.CTRL+Qt.Key_R,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Reset Positions"),
         QT_TRANSLATE_NOOP("action","Reset Positions"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "inspector",
         QT_TRANSLATE_NOOP("action","show inspector"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Inspector"),
         QT_TRANSLATE_NOOP("action","Inspector"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "reset-stretch",
         QT_TRANSLATE_NOOP("action","reset measure stretch"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Reset Stretch"),
         QT_TRANSLATE_NOOP("action","Reset Stretch"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "show-invisible",
         QT_TRANSLATE_NOOP("action","show invisible"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Show Invisible"),
         QT_TRANSLATE_NOOP("action","Show Invisible"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "show-frames",
         QT_TRANSLATE_NOOP("action","show frames"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Show Frames"),
         QT_TRANSLATE_NOOP("action","Show Frames"),
         -1
         ),
      Shortcut(
         SS.STATE_EDIT,
         "show-keys",
         QT_TRANSLATE_NOOP("action","show keyboard"),
         QKeySequence.UnknownKey,
         Qt.Key_F2,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Show Keyboard"),
         QT_TRANSLATE_NOOP("action","Show Keyboard"),
         IconNames2.keys_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "script-debug",
         QT_TRANSLATE_NOOP("action","enable script debugger"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Enable Script Debugger"),
         QT_TRANSLATE_NOOP("action","Enable Script Debugger"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "rest-1",
         QT_TRANSLATE_NOOP("action","enter 1/1 rest"),
         QKeySequence(Qt.SHIFT+Qt.Key_R, Qt.SHIFT+Qt.Key_S),
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","1/1 rest"),
         QT_TRANSLATE_NOOP("action","enter 1/1 rest"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "rest-2",
         QT_TRANSLATE_NOOP("action","enter 1/2 rest"),
         QKeySequence(Qt.SHIFT+Qt.Key_R, Qt.SHIFT+Qt.Key_M),
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","1/2 rest"),
         QT_TRANSLATE_NOOP("action","enter 1/2 rest"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "rest-4",
         QT_TRANSLATE_NOOP("action","enter 1/4 rest"),
         QKeySequence(Qt.SHIFT+Qt.Key_R, Qt.SHIFT+Qt.Key_R),
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","1/4 rest"),
         QT_TRANSLATE_NOOP("action","enter 1/4 rest"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "rest-8",
         QT_TRANSLATE_NOOP("action","enter 1/8 rest"),
         QKeySequence(Qt.SHIFT+Qt.Key_R, Qt.SHIFT+Qt.Key_Q),
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","1/8 rest"),
         QT_TRANSLATE_NOOP("action","enter 1/8 rest"),
         -1
         ),
      Shortcut(                     # mapped to undo in note entry mode
         SS.STATE_NOTE_ENTRY,
         "backspace",
         QT_TRANSLATE_NOOP("action","backspace"),
         QKeySequence(Qt.Key_Backspace),    # QKeySequence.Back,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","backspace"),
         QT_TRANSLATE_NOOP("action","backspace"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_SEARCH,
         "find",
         QT_TRANSLATE_NOOP("action","search"),
         QKeySequence.Find,        # Qt.CTRL + Qt.Key_F,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Search"),
         QT_TRANSLATE_NOOP("action","Search"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY,
         "zoomin",
         QT_TRANSLATE_NOOP("action","Zoom In"),
         Qt.CTRL + Qt.Key_Plus,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Zoom In"),
         QT_TRANSLATE_NOOP("action","Zoom In"),
         -1
         ),
      Shortcut(
         # conflicts with Ctrl+- in edit mode to enter lyrics hyphen
         # SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT,
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "zoomout",
         QT_TRANSLATE_NOOP("action","Zoom Out"),
         Qt.CTRL + Qt.Key_Minus,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Zoom Out"),
         QT_TRANSLATE_NOOP("action","Zoom Out"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "mirror-note",
         QT_TRANSLATE_NOOP("action","mirror note head"),
         Qt.SHIFT + Qt.Key_X,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","mirror note head"),
         QT_TRANSLATE_NOOP("action","mirror note head"),
         IconNames2.flip_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "edit-style",
         QT_TRANSLATE_NOOP("action","Edit General Style..."),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Edit General Style..."),
         QT_TRANSLATE_NOOP("action","Edit General Style..."),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "edit-text-style",
         QT_TRANSLATE_NOOP("action","Edit Text Style..."),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Edit Text Style..."),
         QT_TRANSLATE_NOOP("action","Edit Text Style..."),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "edit-harmony",
         QT_TRANSLATE_NOOP("action","Edit Chord Style..."),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Edit Chord Style..."),
         QT_TRANSLATE_NOOP("action","Edit Chord Style..."),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "select-similar",
         QT_TRANSLATE_NOOP("action","Select all similar elements"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","All Similar Elements"),
         QT_TRANSLATE_NOOP("action","All Similar Elements"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "select-similar-staff",
         QT_TRANSLATE_NOOP("action","Select all similar elements in same staff"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","All Similar Elements in Same Staff"),
         QT_TRANSLATE_NOOP("action","All Similar Elements in Same Staff"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "synth-control",
         QT_TRANSLATE_NOOP("action","Synthesizer"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Synthesizer"),
         QT_TRANSLATE_NOOP("action","Synthesizer Control"),
         -1
         ),
      Shortcut(
         SS.STATE_NOTE_ENTRY,
         "double-duration",
         QT_TRANSLATE_NOOP("action","double duration"),
         QKeySequence(Qt.Key_W),
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","double duration"),
         QT_TRANSLATE_NOOP("action","double duration"),
         -1
         ),
      Shortcut(
         SS.STATE_NOTE_ENTRY,
         "half-duration",
         QT_TRANSLATE_NOOP("action","half duration"),
         QKeySequence(Qt.Key_Q),
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","half duration"),
         QT_TRANSLATE_NOOP("action","half duration"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY,
         "repeat-sel",
         QT_TRANSLATE_NOOP("action","repeat selection"),
         QKeySequence.UnknownKey,
         Qt.Key_R,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Repeat selection"),
         QT_TRANSLATE_NOOP("action","Repeat selection"),
         IconNames2.fileOpen_ICON
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "follow",
         QT_TRANSLATE_NOOP("action","follow song"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Follow Song"),
         QT_TRANSLATE_NOOP("action","Follow Song"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "split-h",
         QT_TRANSLATE_NOOP("action","split window horizontal"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Documents Side by Side"),
         QT_TRANSLATE_NOOP("action","Documents Side by Side"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "split-v",
         QT_TRANSLATE_NOOP("action","split window vertical"),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Documents Stacked"),
         QT_TRANSLATE_NOOP("action","Documents Stacked"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_PLAY,
         "parts",
         QT_TRANSLATE_NOOP("action","Parts..."),
         QKeySequence.UnknownKey,
         0,
         Qt.WindowShortcut,
         QT_TRANSLATE_NOOP("action","Parts..."),
         QT_TRANSLATE_NOOP("action","Parts..."),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "next-score",
         QT_TRANSLATE_NOOP("action","next score"),
         QKeySequence.NextChild,
         0,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","next score"),
         QT_TRANSLATE_NOOP("action","next score"),
         -1
         ),
      Shortcut(
         SS.STATE_NORMAL,
         "previous-score",
         QT_TRANSLATE_NOOP("action","previous score"),
         Qt.CTRL+Qt.SHIFT+Qt.Key_Tab,
         0,
         Qt.ApplicationShortcut,
         QT_TRANSLATE_NOOP("action","previous score"),
         QT_TRANSLATE_NOOP("action","previous score"),
         -1
         ),
      Shortcut(
         SS.STATE_INIT | SS.STATE_DISABLED | SS.STATE_NORMAL | SS.STATE_NOTE_ENTRY | SS.STATE_EDIT | SS.STATE_PLAY | SS.STATE_SEARCH,
         "musescore-connect",
         "MuseScore Connect",
         QKeySequence.UnknownKey,
         Qt.Key_F7,
         Qt.ApplicationShortcut,
         "MuseScore Connect",
         "MuseScore Connect",
         IconNames2.community_ICON
         )
      ]
