# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagesettings.ui'
#
# Created: Sun Jun 28 10:39:18 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PageSettingsBase(object):
    def setupUi(self, PageSettingsBase):
        PageSettingsBase.setObjectName(_fromUtf8("PageSettingsBase"))
        PageSettingsBase.resize(777, 436)
        self.gridlayout = QtGui.QGridLayout(PageSettingsBase)
        self.gridlayout.setMargin(8)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.previewGroup = QtGui.QGroupBox(PageSettingsBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previewGroup.sizePolicy().hasHeightForWidth())
        self.previewGroup.setSizePolicy(sizePolicy)
        self.previewGroup.setObjectName(_fromUtf8("previewGroup"))
        self.gridlayout.addWidget(self.previewGroup, 0, 2, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        spacerItem = QtGui.QSpacerItem(131, 31, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.buttonApply = QtGui.QPushButton(PageSettingsBase)
        self.buttonApply.setObjectName(_fromUtf8("buttonApply"))
        self.hboxlayout.addWidget(self.buttonApply)
        self.buttonOk = QtGui.QPushButton(PageSettingsBase)
        self.buttonOk.setObjectName(_fromUtf8("buttonOk"))
        self.hboxlayout.addWidget(self.buttonOk)
        self.buttonCancel = QtGui.QPushButton(PageSettingsBase)
        self.buttonCancel.setObjectName(_fromUtf8("buttonCancel"))
        self.hboxlayout.addWidget(self.buttonCancel)
        self.gridlayout.addLayout(self.hboxlayout, 1, 0, 1, 3)
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.groupBox = QtGui.QGroupBox(PageSettingsBase)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout1.setMargin(8)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.pageWidth = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageWidth.sizePolicy().hasHeightForWidth())
        self.pageWidth.setSizePolicy(sizePolicy)
        self.pageWidth.setMaximum(2000.0)
        self.pageWidth.setObjectName(_fromUtf8("pageWidth"))
        self.gridlayout1.addWidget(self.pageWidth, 1, 1, 1, 1)
        self.pageHeight = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageHeight.sizePolicy().hasHeightForWidth())
        self.pageHeight.setSizePolicy(sizePolicy)
        self.pageHeight.setMaximum(2000.0)
        self.pageHeight.setObjectName(_fromUtf8("pageHeight"))
        self.gridlayout1.addWidget(self.pageHeight, 2, 1, 1, 1)
        self.twosided = QtGui.QCheckBox(self.groupBox)
        self.twosided.setObjectName(_fromUtf8("twosided"))
        self.gridlayout1.addWidget(self.twosided, 4, 0, 1, 2)
        self.landscape = QtGui.QCheckBox(self.groupBox)
        self.landscape.setObjectName(_fromUtf8("landscape"))
        self.gridlayout1.addWidget(self.landscape, 3, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout1.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout1.addWidget(self.label_2, 1, 0, 1, 1)
        self.pageGroup = QtGui.QComboBox(self.groupBox)
        self.pageGroup.setObjectName(_fromUtf8("pageGroup"))
        self.gridlayout1.addWidget(self.pageGroup, 0, 0, 1, 2)
        self.vboxlayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(PageSettingsBase)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.hboxlayout1 = QtGui.QHBoxLayout(self.groupBox_2)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(8)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout1.addWidget(self.label)
        self.spatiumEntry = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spatiumEntry.sizePolicy().hasHeightForWidth())
        self.spatiumEntry.setSizePolicy(sizePolicy)
        self.spatiumEntry.setDecimals(3)
        self.spatiumEntry.setMinimum(0.001)
        self.spatiumEntry.setMaximum(999.99)
        self.spatiumEntry.setSingleStep(0.2)
        self.spatiumEntry.setProperty("value", 2.001)
        self.spatiumEntry.setObjectName(_fromUtf8("spatiumEntry"))
        self.hboxlayout1.addWidget(self.spatiumEntry)
        self.vboxlayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_12 = QtGui.QLabel(PageSettingsBase)
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.pageOffsetEntry = QtGui.QSpinBox(PageSettingsBase)
        self.pageOffsetEntry.setMinimum(1)
        self.pageOffsetEntry.setMaximum(999)
        self.pageOffsetEntry.setObjectName(_fromUtf8("pageOffsetEntry"))
        self.horizontalLayout_2.addWidget(self.pageOffsetEntry)
        self.vboxlayout.addLayout(self.horizontalLayout_2)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(8)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.mmButton = QtGui.QRadioButton(PageSettingsBase)
        self.mmButton.setObjectName(_fromUtf8("mmButton"))
        self.vboxlayout1.addWidget(self.mmButton)
        self.inchButton = QtGui.QRadioButton(PageSettingsBase)
        self.inchButton.setObjectName(_fromUtf8("inchButton"))
        self.vboxlayout1.addWidget(self.inchButton)
        self.vboxlayout.addLayout(self.vboxlayout1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.gridlayout.addLayout(self.vboxlayout, 0, 0, 1, 1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.groupBox_3 = QtGui.QGroupBox(PageSettingsBase)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridlayout2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridlayout2.setMargin(8)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.evenPageBottomMargin = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evenPageBottomMargin.sizePolicy().hasHeightForWidth())
        self.evenPageBottomMargin.setSizePolicy(sizePolicy)
        self.evenPageBottomMargin.setMaximum(2000.0)
        self.evenPageBottomMargin.setObjectName(_fromUtf8("evenPageBottomMargin"))
        self.gridlayout2.addWidget(self.evenPageBottomMargin, 3, 1, 1, 1)
        self.evenPageTopMargin = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evenPageTopMargin.sizePolicy().hasHeightForWidth())
        self.evenPageTopMargin.setSizePolicy(sizePolicy)
        self.evenPageTopMargin.setMaximum(2000.0)
        self.evenPageTopMargin.setObjectName(_fromUtf8("evenPageTopMargin"))
        self.gridlayout2.addWidget(self.evenPageTopMargin, 2, 1, 1, 1)
        self.evenPageRightMargin = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evenPageRightMargin.sizePolicy().hasHeightForWidth())
        self.evenPageRightMargin.setSizePolicy(sizePolicy)
        self.evenPageRightMargin.setMaximum(2000.0)
        self.evenPageRightMargin.setObjectName(_fromUtf8("evenPageRightMargin"))
        self.gridlayout2.addWidget(self.evenPageRightMargin, 1, 1, 1, 1)
        self.evenPageLeftMargin = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evenPageLeftMargin.sizePolicy().hasHeightForWidth())
        self.evenPageLeftMargin.setSizePolicy(sizePolicy)
        self.evenPageLeftMargin.setMaximum(2000.0)
        self.evenPageLeftMargin.setObjectName(_fromUtf8("evenPageLeftMargin"))
        self.gridlayout2.addWidget(self.evenPageLeftMargin, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridlayout2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridlayout2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridlayout2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridlayout2.addWidget(self.label_4, 0, 0, 1, 1)
        self.vboxlayout2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(PageSettingsBase)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridlayout3 = QtGui.QGridLayout(self.groupBox_4)
        self.gridlayout3.setMargin(8)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.oddPageBottomMargin = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddPageBottomMargin.sizePolicy().hasHeightForWidth())
        self.oddPageBottomMargin.setSizePolicy(sizePolicy)
        self.oddPageBottomMargin.setMaximum(2000.0)
        self.oddPageBottomMargin.setObjectName(_fromUtf8("oddPageBottomMargin"))
        self.gridlayout3.addWidget(self.oddPageBottomMargin, 3, 1, 1, 1)
        self.oddPageTopMargin = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddPageTopMargin.sizePolicy().hasHeightForWidth())
        self.oddPageTopMargin.setSizePolicy(sizePolicy)
        self.oddPageTopMargin.setMaximum(2000.0)
        self.oddPageTopMargin.setObjectName(_fromUtf8("oddPageTopMargin"))
        self.gridlayout3.addWidget(self.oddPageTopMargin, 2, 1, 1, 1)
        self.oddPageRightMargin = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddPageRightMargin.sizePolicy().hasHeightForWidth())
        self.oddPageRightMargin.setSizePolicy(sizePolicy)
        self.oddPageRightMargin.setMaximum(2000.0)
        self.oddPageRightMargin.setObjectName(_fromUtf8("oddPageRightMargin"))
        self.gridlayout3.addWidget(self.oddPageRightMargin, 1, 1, 1, 1)
        self.oddPageLeftMargin = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oddPageLeftMargin.sizePolicy().hasHeightForWidth())
        self.oddPageLeftMargin.setSizePolicy(sizePolicy)
        self.oddPageLeftMargin.setMaximum(2000.0)
        self.oddPageLeftMargin.setObjectName(_fromUtf8("oddPageLeftMargin"))
        self.gridlayout3.addWidget(self.oddPageLeftMargin, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridlayout3.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridlayout3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridlayout3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridlayout3.addWidget(self.label_8, 0, 0, 1, 1)
        self.vboxlayout2.addWidget(self.groupBox_4)
        self.gridlayout.addLayout(self.vboxlayout2, 0, 1, 1, 1)
        self.label_3.setBuddy(self.pageHeight)
        self.label_2.setBuddy(self.pageWidth)
        self.label.setBuddy(self.spatiumEntry)
        self.label_12.setBuddy(self.pageOffsetEntry)
        self.label_7.setBuddy(self.evenPageBottomMargin)
        self.label_6.setBuddy(self.evenPageTopMargin)
        self.label_5.setBuddy(self.evenPageRightMargin)
        self.label_4.setBuddy(self.evenPageLeftMargin)
        self.label_11.setBuddy(self.oddPageBottomMargin)
        self.label_10.setBuddy(self.oddPageTopMargin)
        self.label_9.setBuddy(self.oddPageRightMargin)
        self.label_8.setBuddy(self.oddPageLeftMargin)

        self.retranslateUi(PageSettingsBase)
        QtCore.QObject.connect(self.buttonOk, QtCore.SIGNAL(_fromUtf8("clicked()")), PageSettingsBase.accept)
        QtCore.QObject.connect(self.buttonCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), PageSettingsBase.reject)
        QtCore.QMetaObject.connectSlotsByName(PageSettingsBase)
        PageSettingsBase.setTabOrder(self.buttonApply, self.buttonOk)
        PageSettingsBase.setTabOrder(self.buttonOk, self.buttonCancel)
        PageSettingsBase.setTabOrder(self.buttonCancel, self.pageGroup)
        PageSettingsBase.setTabOrder(self.pageGroup, self.pageWidth)
        PageSettingsBase.setTabOrder(self.pageWidth, self.pageHeight)
        PageSettingsBase.setTabOrder(self.pageHeight, self.landscape)
        PageSettingsBase.setTabOrder(self.landscape, self.twosided)
        PageSettingsBase.setTabOrder(self.twosided, self.spatiumEntry)
        PageSettingsBase.setTabOrder(self.spatiumEntry, self.pageOffsetEntry)
        PageSettingsBase.setTabOrder(self.pageOffsetEntry, self.mmButton)
        PageSettingsBase.setTabOrder(self.mmButton, self.inchButton)
        PageSettingsBase.setTabOrder(self.inchButton, self.evenPageLeftMargin)
        PageSettingsBase.setTabOrder(self.evenPageLeftMargin, self.evenPageRightMargin)
        PageSettingsBase.setTabOrder(self.evenPageRightMargin, self.evenPageTopMargin)
        PageSettingsBase.setTabOrder(self.evenPageTopMargin, self.evenPageBottomMargin)
        PageSettingsBase.setTabOrder(self.evenPageBottomMargin, self.oddPageLeftMargin)
        PageSettingsBase.setTabOrder(self.oddPageLeftMargin, self.oddPageRightMargin)
        PageSettingsBase.setTabOrder(self.oddPageRightMargin, self.oddPageTopMargin)
        PageSettingsBase.setTabOrder(self.oddPageTopMargin, self.oddPageBottomMargin)

    def retranslateUi(self, PageSettingsBase):
        PageSettingsBase.setWindowTitle(_translate("PageSettingsBase", "MuseScore: Page Settings", None))
        self.previewGroup.setTitle(_translate("PageSettingsBase", "Preview", None))
        self.buttonApply.setText(_translate("PageSettingsBase", "Apply", None))
        self.buttonOk.setText(_translate("PageSettingsBase", "OK", None))
        self.buttonCancel.setText(_translate("PageSettingsBase", "Cancel", None))
        self.groupBox.setTitle(_translate("PageSettingsBase", "Page Size", None))
        self.twosided.setText(_translate("PageSettingsBase", "Two Sided", None))
        self.landscape.setText(_translate("PageSettingsBase", "Landscape", None))
        self.label_3.setText(_translate("PageSettingsBase", "Height", None))
        self.label_2.setText(_translate("PageSettingsBase", "Width", None))
        self.groupBox_2.setTitle(_translate("PageSettingsBase", "Scaling", None))
        self.label.setText(_translate("PageSettingsBase", "Space", None))
        self.label_12.setText(_translate("PageSettingsBase", "First page no.", None))
        self.mmButton.setText(_translate("PageSettingsBase", "mm", None))
        self.inchButton.setText(_translate("PageSettingsBase", "inch", None))
        self.groupBox_3.setTitle(_translate("PageSettingsBase", "Even Page Margins", None))
        self.label_7.setText(_translate("PageSettingsBase", "Bottom Margin", None))
        self.label_6.setText(_translate("PageSettingsBase", "Top Margin", None))
        self.label_5.setText(_translate("PageSettingsBase", "Right Margin", None))
        self.label_4.setText(_translate("PageSettingsBase", "Left Margin", None))
        self.groupBox_4.setTitle(_translate("PageSettingsBase", "Odd Page Margins", None))
        self.label_11.setText(_translate("PageSettingsBase", "Bottom Margin", None))
        self.label_10.setText(_translate("PageSettingsBase", "Top Margin", None))
        self.label_9.setText(_translate("PageSettingsBase", "Right Margin", None))
        self.label_8.setText(_translate("PageSettingsBase", "Left Margin", None))

