# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prefsdialog.ui'
#
# Created: Fri Jun 26 21:14:50 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PrefsDialogBase(object):
    def setupUi(self, PrefsDialogBase):
        PrefsDialogBase.setObjectName(_fromUtf8("PrefsDialogBase"))
        PrefsDialogBase.resize(780, 592)
        self.verticalLayout_7 = QtGui.QVBoxLayout(PrefsDialogBase)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.General = QtGui.QTabWidget(PrefsDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.General.sizePolicy().hasHeightForWidth())
        self.General.setSizePolicy(sizePolicy)
        self.General.setAccessibleName(_fromUtf8(""))
        self.General.setObjectName(_fromUtf8("General"))
        self.tab = QtGui.QWidget()
        self.tab.setAccessibleName(_fromUtf8(""))
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.emptySession = QtGui.QRadioButton(self.groupBox_5)
        self.emptySession.setObjectName(_fromUtf8("emptySession"))
        self.verticalLayout_3.addWidget(self.emptySession)
        self.lastSession = QtGui.QRadioButton(self.groupBox_5)
        self.lastSession.setChecked(True)
        self.lastSession.setObjectName(_fromUtf8("lastSession"))
        self.verticalLayout_3.addWidget(self.lastSession)
        self.newSession = QtGui.QRadioButton(self.groupBox_5)
        self.newSession.setObjectName(_fromUtf8("newSession"))
        self.verticalLayout_3.addWidget(self.newSession)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.scoreSession = QtGui.QRadioButton(self.groupBox_5)
        self.scoreSession.setObjectName(_fromUtf8("scoreSession"))
        self.horizontalLayout_2.addWidget(self.scoreSession)
        self.sessionScore = QtGui.QLineEdit(self.groupBox_5)
        self.sessionScore.setObjectName(_fromUtf8("sessionScore"))
        self.horizontalLayout_2.addWidget(self.sessionScore)
        self.startWithButton = QtGui.QToolButton(self.groupBox_5)
        self.startWithButton.setAccessibleName(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/data/fileopen.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startWithButton.setIcon(icon)
        self.startWithButton.setObjectName(_fromUtf8("startWithButton"))
        self.horizontalLayout_2.addWidget(self.startWithButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.showSplashScreen = QtGui.QCheckBox(self.groupBox_5)
        self.showSplashScreen.setObjectName(_fromUtf8("showSplashScreen"))
        self.verticalLayout_3.addWidget(self.showSplashScreen)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.tab)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.language = QtGui.QComboBox(self.groupBox_10)
        self.language.setObjectName(_fromUtf8("language"))
        self.verticalLayout.addWidget(self.language)
        self.restartWarning_2 = QtGui.QLabel(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restartWarning_2.sizePolicy().hasHeightForWidth())
        self.restartWarning_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 1, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 1, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 119, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.restartWarning_2.setPalette(palette)
        self.restartWarning_2.setTextFormat(QtCore.Qt.PlainText)
        self.restartWarning_2.setWordWrap(True)
        self.restartWarning_2.setObjectName(_fromUtf8("restartWarning_2"))
        self.verticalLayout.addWidget(self.restartWarning_2)
        self.gridLayout_2.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_6)
        self.gridlayout.setMargin(3)
        self.gridlayout.setHorizontalSpacing(3)
        self.gridlayout.setVerticalSpacing(0)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridlayout.addWidget(self.label_26, 0, 0, 1, 1)
        self.instrumentList = QtGui.QLineEdit(self.groupBox_6)
        self.instrumentList.setObjectName(_fromUtf8("instrumentList"))
        self.gridlayout.addWidget(self.instrumentList, 0, 1, 1, 1)
        self.instrumentListButton = QtGui.QToolButton(self.groupBox_6)
        self.instrumentListButton.setIcon(icon)
        self.instrumentListButton.setObjectName(_fromUtf8("instrumentListButton"))
        self.gridlayout.addWidget(self.instrumentListButton, 0, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridlayout.addWidget(self.label_23, 1, 0, 1, 1)
        self.workingDirectory = QtGui.QLineEdit(self.groupBox_6)
        self.workingDirectory.setObjectName(_fromUtf8("workingDirectory"))
        self.gridlayout.addWidget(self.workingDirectory, 1, 1, 1, 1)
        self.workingDirectoryButton = QtGui.QToolButton(self.groupBox_6)
        self.workingDirectoryButton.setIcon(icon)
        self.workingDirectoryButton.setObjectName(_fromUtf8("workingDirectoryButton"))
        self.gridlayout.addWidget(self.workingDirectoryButton, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_6, 1, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout1.setMargin(3)
        self.gridlayout1.setSpacing(3)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.playPanelShow = QtGui.QCheckBox(self.groupBox)
        self.playPanelShow.setObjectName(_fromUtf8("playPanelShow"))
        self.gridlayout1.addWidget(self.playPanelShow, 0, 0, 1, 1)
        self.navigatorShow = QtGui.QCheckBox(self.groupBox)
        self.navigatorShow.setObjectName(_fromUtf8("navigatorShow"))
        self.gridlayout1.addWidget(self.navigatorShow, 1, 0, 1, 1)
        self.webPanelShow = QtGui.QCheckBox(self.groupBox)
        self.webPanelShow.setObjectName(_fromUtf8("webPanelShow"))
        self.gridlayout1.addWidget(self.webPanelShow, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(self.tab)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.styleCombo = QtGui.QComboBox(self.groupBox_14)
        self.styleCombo.setObjectName(_fromUtf8("styleCombo"))
        self.verticalLayout_4.addWidget(self.styleCombo)
        self.gridLayout_2.addWidget(self.groupBox_14, 2, 1, 1, 1)
        self.autoSave = QtGui.QGroupBox(self.tab)
        self.autoSave.setFlat(False)
        self.autoSave.setCheckable(True)
        self.autoSave.setObjectName(_fromUtf8("autoSave"))
        self.hboxlayout = QtGui.QHBoxLayout(self.autoSave)
        self.hboxlayout.setSpacing(3)
        self.hboxlayout.setMargin(3)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label_25 = QtGui.QLabel(self.autoSave)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.hboxlayout.addWidget(self.label_25)
        self.autoSaveTime = QtGui.QSpinBox(self.autoSave)
        self.autoSaveTime.setMinimum(1)
        self.autoSaveTime.setProperty("value", 2)
        self.autoSaveTime.setObjectName(_fromUtf8("autoSaveTime"))
        self.hboxlayout.addWidget(self.autoSaveTime)
        self.label_27 = QtGui.QLabel(self.autoSave)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.hboxlayout.addWidget(self.label_27)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.autoSave, 3, 0, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.tab)
        self.groupBox_12.setFlat(False)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_30 = QtGui.QLabel(self.groupBox_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_3.addWidget(self.label_30, 0, 0, 1, 2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_28 = QtGui.QLabel(self.groupBox_12)
        self.label_28.setTextFormat(QtCore.Qt.PlainText)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_28)
        self.iconWidth = QtGui.QSpinBox(self.groupBox_12)
        self.iconWidth.setMinimum(2)
        self.iconWidth.setMaximum(72)
        self.iconWidth.setProperty("value", 24)
        self.iconWidth.setObjectName(_fromUtf8("iconWidth"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.iconWidth)
        self.gridLayout_3.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_29 = QtGui.QLabel(self.groupBox_12)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_29)
        self.iconHeight = QtGui.QSpinBox(self.groupBox_12)
        self.iconHeight.setMinimum(2)
        self.iconHeight.setMaximum(72)
        self.iconHeight.setProperty("value", 24)
        self.iconHeight.setObjectName(_fromUtf8("iconHeight"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.iconHeight)
        self.gridLayout_3.addLayout(self.formLayout_3, 1, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_12)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 2, 0, 1, 2)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_32 = QtGui.QLabel(self.groupBox_12)
        self.label_32.setTextFormat(QtCore.Qt.PlainText)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_32)
        self.noteEntryIconWidth = QtGui.QSpinBox(self.groupBox_12)
        self.noteEntryIconWidth.setMinimum(2)
        self.noteEntryIconWidth.setMaximum(72)
        self.noteEntryIconWidth.setProperty("value", 24)
        self.noteEntryIconWidth.setObjectName(_fromUtf8("noteEntryIconWidth"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.noteEntryIconWidth)
        self.gridLayout_3.addLayout(self.formLayout_4, 3, 0, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.noteEntryIconHeight = QtGui.QSpinBox(self.groupBox_12)
        self.noteEntryIconHeight.setMinimum(2)
        self.noteEntryIconHeight.setMaximum(72)
        self.noteEntryIconHeight.setProperty("value", 24)
        self.noteEntryIconHeight.setObjectName(_fromUtf8("noteEntryIconHeight"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.noteEntryIconHeight)
        self.label_33 = QtGui.QLabel(self.groupBox_12)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_33)
        self.gridLayout_3.addLayout(self.formLayout_5, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_12, 3, 1, 2, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.tab)
        self.groupBox_13.setFlat(False)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.applicationFont = QtGui.QFontComboBox(self.groupBox_13)
        self.applicationFont.setObjectName(_fromUtf8("applicationFont"))
        self.horizontalLayout.addWidget(self.applicationFont)
        self.applicationFontSize = QtGui.QSpinBox(self.groupBox_13)
        self.applicationFontSize.setMinimum(6)
        self.applicationFontSize.setMaximum(72)
        self.applicationFontSize.setProperty("value", 10)
        self.applicationFontSize.setObjectName(_fromUtf8("applicationFontSize"))
        self.horizontalLayout.addWidget(self.applicationFontSize)
        self.gridLayout_2.addWidget(self.groupBox_13, 4, 0, 1, 1)
        self.General.addTab(self.tab, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setAccessibleName(_fromUtf8(""))
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.vboxlayout = QtGui.QVBoxLayout(self.tab2)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab2)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.bgWallpaperButton = QtGui.QRadioButton(self.groupBox_2)
        self.bgWallpaperButton.setObjectName(_fromUtf8("bgWallpaperButton"))
        self.gridlayout2.addWidget(self.bgWallpaperButton, 0, 1, 1, 1)
        self.bgColorButton = QtGui.QRadioButton(self.groupBox_2)
        self.bgColorButton.setObjectName(_fromUtf8("bgColorButton"))
        self.gridlayout2.addWidget(self.bgColorButton, 0, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.bgWallpaper = QtGui.QLineEdit(self.groupBox_2)
        self.bgWallpaper.setObjectName(_fromUtf8("bgWallpaper"))
        self.hboxlayout1.addWidget(self.bgWallpaper)
        self.bgWallpaperSelect = QtGui.QToolButton(self.groupBox_2)
        self.bgWallpaperSelect.setIcon(icon)
        self.bgWallpaperSelect.setObjectName(_fromUtf8("bgWallpaperSelect"))
        self.hboxlayout1.addWidget(self.bgWallpaperSelect)
        self.gridlayout2.addLayout(self.hboxlayout1, 1, 1, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
